### ISSUE TITLE
Can't run server

### ISSUE THREAD

**Issue by V1t3r** [derand/kanojo_server#1]
Traceback (most recent call last):
  File "web_job.py", line 20, in <module>
    from activity import FILL_TYPE_HTML
  File "/home/v1t3r/kanojo_server-0.3.4/activity.py", line 13, in <module>
    from web_job import getCategoryText
  File "/home/v1t3r/kanojo_server-0.3.4/web_job.py", line 20, in <module>
    from activity import FILL_TYPE_HTML
ImportError: cannot import name 'FILL_TYPE_HTML' from 'activity' (/home/v1t3r/kanojo_server-0.3.4/activity.py)

0.3.3 runs the same. 0.3.2 works fine

**Comment by V1t3r** [comment]
Не могу стартонуть сервер на Debian 10(стоит python 3.7 - все модули из requirements.txt стоят).
